language: scala
sudo: false
jdk: oraclejdk8
scala:
- 2.11.8
notifications:
  slack:
    secure: C+UMkD+eaaeTJvbEa82vdmNMvFpLgncLU7KDCy+5fUk0Nb1rUVxQ4GrYuqBUDC9g3OvVmKpn3KwCywcohuMMMVsxeHY4tpuUdyjfZSjxnf53TgJk6rBtH0zvMAy57RXJ1AUIyHmIH8jMF3LEAlRDAI3bVd84V6ej4GO3OK0ii79vDdRxuHUxnPN8JCYF8pspSrUp9DahR0asCNBswDCNhIAw5k9y0vABXseVzqLBsvfTWLZ9ZbuN3h0Zjh4j0YP4UHUm7JRp845zBbaStNHEss8DhG0dyKZR/nDuWcSzlfscJ+HnIGrgTIX7XNRZwvVuVtbOPvhS6MPm6XdX2oVL4lXG4HP/FEp4LDt0zJ+v8l+wfaW+uQkOR52a+MTVWYcWD9zOq/T01Z48oCV8sEAPP9LmUrjMH4gGb4iXwUniBLZGqra6NHu7sBZ2LKeHzVX483KAbSdcChaUV8uHPf0CmVN37Jq1LDmGVGmE6F9tRDy3amypTXKSpuyo6HqHZogrP1NO2wkxZ4/tb7hT4n/ie74pQOaioVUvX2n1xnZccxZUdfLczDhBADLFK/ekRx+KnmG0CCD3C41lCxAqSo270d39qm0k2NN3P9hYuI6nEBypLzWnbdEOx4i67Tt15Qab3QCI2W0IOxO+fL4eANXZjqkIfjH9+BPiOBNyYlpOnPU=
